import axios from 'axios'

// In production builds, set VITE_API_BASE_URL in your .env.production file
const BASE_URL = import.meta.env.VITE_API_BASE_URL
  ? `${import.meta.env.VITE_API_BASE_URL}`
  : '/api'

const api = axios.create({
  baseURL: BASE_URL,
})

api.interceptors.response.use(
  res => res.data,
  err => {
    const msg = err.response?.data?.error || err.message || 'Request failed'
    return Promise.reject(new Error(msg))
  }
)

export const analyzeFiles = (files, userInput = '') => {
  const form = new FormData()
  if (files && files.length > 0) {
    files.forEach(f => form.append('files', f))
  }
  if (userInput) {
    form.append('user_input', userInput)
  }
  return api.post('/analyze', form, {
    headers: { 'Content-Type': 'multipart/form-data' },
  })
}

export const getProcess = (id) => api.get(`/processes/${id}`)
export const listProcesses = () => api.get('/processes')
export const getAutomation = (id) => api.get(`/processes/${id}/automation`)

// In-memory promise caches — share in-flight requests across components.
const flowCache = new Map()
const archCache = new Map()

export const getProcessFlow = (id) => {
  if (flowCache.has(id)) return flowCache.get(id)
  const promise = api.get(`/processes/${id}/flow`).catch(err => {
    flowCache.delete(id)
    throw err
  })
  flowCache.set(id, promise)
  return promise
}

export const getAutomationArchitecture = (id) => {
  if (archCache.has(id)) return archCache.get(id)
  const promise = api.get(`/suggestions/${id}/architecture`).catch(err => {
    archCache.delete(id)
    throw err
  })
  archCache.set(id, promise)
  return promise
}

export const getTechnicalDesign = (id) => api.get(`/suggestions/${id}/technical-design`)
export const runAutomationArchitecture = (data) => api.post(`/agent/run`, data)
export const loginUser = (email, password) => api.post('/login', { email, password })


/* ════════════════════════════════════════════════════════════════════════════
   ▼ NEW endpoints for the spec features                                    ▼
   ════════════════════════════════════════════════════════════════════════════ */

/**
 * NEW: AgentForgeX-scoped chatbot.
 *
 *   sendChatMessage("Explain process", "p2p-abc123")
 *
 * Returns: { status, answer, in_scope, intent, process_key }
 * On out-of-scope queries, the backend returns the canonical out-of-scope
 * message but still status:true so the UI just renders it as a bot reply.
 */
export const sendChatMessage = (query, processKey = null) =>
  api.post('/chatbot/ask', { query, process_key: processKey })

/**
 * NEW: Download the auto-generated source code ZIP for a suggestion.
 *
 * Triggers a browser download of `agentforgex_<slug>.zip` containing the
 * orchestrator, per-agent files, per-tool files, ETL scripts, pipeline.yaml,
 * connections.yaml, run/deploy scripts and tests.
 *
 * Returns a Promise that resolves once the download has started.  Caller
 * should show a loader between resolve/reject.
 */
export const downloadSuggestionCode = async (suggestionId) => {
  // Use Axios to fetch the binary ZIP file.
  // This keeps the loader spinning on the button until the file is generated by the server (~50 seconds).
  const blob = await api.get(`/suggestions/${suggestionId}/download-code`, {
    responseType: 'blob',
  })

  const blobUrl = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = blobUrl
  a.download = `agentforgex_${suggestionId}.zip`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(blobUrl), 1000)

  return { filename: `agentforgex_${suggestionId}.zip` }
}

export default api
